webtalk_init -webtalk_dir C:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.sim/sim_1/synth/timing/xsim/xsim.dir/tb_fc_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 28 15:30:18 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0d473f79-f823-41be-b388-602769278d2d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ca960a0462f142f79fd6ebf44e8582af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "17" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "3149 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "905 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "24729" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "996" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "19.97_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "452876_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1761440086 -regid "" -xml C:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.sim/sim_1/synth/timing/xsim/xsim.dir/tb_fc_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.sim/sim_1/synth/timing/xsim/xsim.dir/tb_fc_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.sim/sim_1/synth/timing/xsim/xsim.dir/tb_fc_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
