# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.srcs/sources_1/ip/bram_32x16/bram_32x16.xci
# IP: The module: 'bram_32x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.srcs/sources_1/ip/bram_32x16/bram_32x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_32x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.srcs/sources_1/ip/bram_32x16/bram_32x16.xci
# IP: The module: 'bram_32x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/digital-systems-lab/Lab7/Lab7/Lab7.srcs/sources_1/ip/bram_32x16/bram_32x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_32x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
