# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/DELL/OneDrive - SNU/Documents/2022-2/digital-systems/lab/Lab6/Lab6_revised/Lab6/student/Nexys4DDR_Master.xdc

# IP: ip/blk_mem_gen_1_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
